package entity.returndetails;

import java.io.Serializable;
import java.util.Date;

public class ReturnOrderDetail implements Serializable {
   
    private String return_id;
 
    private Integer user_id;

    private Integer shop_id;

    private String market_place_id;

    private String item_id;

    private String transaction_id;

    private Integer item_listing_site_id;

    private Integer item_return_quantity;

    private String item_title;

    private String item_pic_url;

    private Date item_transaction_date_value;

    private String item_price_currency;

    private Double item_price_value;

    private Boolean item_ebay_plus_txn;

    private String buyer_login_name;

    private String seller_login_name;

    private String buyer_email_address;

    private String seller_email_address;

    private String check_out_type;

    private String response_history;

    private String itemized_refund_details;

    private Boolean is_rtn_shipping_editable;

    private Double actual_refund_detail_total_amount_value;

    private String actual_refund_detail_total_amount_currency;

    private String itemized_refund_detail;

    private String refund_status;

    private Date refund_issued_date_value;

    private Date hold_creation_date_value;

    private Date hold_release_date_value;

    private String hold_status;

    private String hold_reference_id;

    private String hold_transaction_id;

    private String money_movement_info;
    
    private String buyer_address_name;
   
    private String buyer_address_country;

    private String buyer_address_postal_code;

    private String buyer_address_state_or_province;

    private String buyer_address_city;
    
    private String buyer_address_address_line1;
   
    private String buyer_address_address_line2;

    private String seller_address_name;

    private String seller_address_country;

    private String seller_address_postal_code;
    
    private String seller_address_state_or_province;

    private String seller_address_city;

    private String seller_address_address_line1;

    private String seller_address_address_line2;

    private String return_shipment_info_shipping_method;

    private String return_shipment_shipped_by;

    private Integer return_shipment_carrier_id;

    private String return_shipment_carrier_enum;
  
    private String return_shipment_carrier_name;

    private String return_shipment_carrier_used;

    private String return_shipment_delivery_status;

    private String return_shipment_destination_address_name;

    private String return_shipment_destination_address_country;

    private String return_shipment_destination_address_postal_code;

    private String return_shipment_destination_address_state_or_province;

    private String return_shipment_destination_address_city;

    private String return_shipment_destination_address__line1;

    private String return_shipment_destination_address__line2;

    private String return_shipment_origin_address_name;

    private String return_shipment_origin_address_country;

    private String return_shipment_origin_address_postal_code;

    private String return_shipment_origin_address_state_or_province;

    private String return_shipment_origin_address_city;

    private String return_shipment_origin_address_line1;

    private String return_shipment_origin_address_line2;

    private Boolean return_shipment_mark_as_received;

    private Boolean return_shipment_active;

    private Boolean return_shipment_label_print_expired;

    private Boolean return_shipment_label_void_expired;

    private Double shipping_label_cost_total_amount_value;

    private String shipping_label_cost_total_amount_currency;

    private String itemized_return_shipping_cost;

    private String payee;

    private String all_shipment_trackings;

    private String return_close_reason;

    private String buyer_close_reason;

    private static final long serialVersionUID = 1L;

    public String getReturn_id() {
        return return_id;
    }

    public void setReturn_id(String return_id) {
        this.return_id = return_id == null ? null : return_id.trim();
    }

    public Integer getUser_id() {
        return user_id;
    }

    
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.shop_id
     *
     * @return the value of return_order_detail.shop_id
     *
     * @mbggenerated
     */
    public Integer getShop_id() {
        return shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.shop_id
     *
     * @param shop_id the value for return_order_detail.shop_id
     *
     * @mbggenerated
     */
    public void setShop_id(Integer shop_id) {
        this.shop_id = shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.market_place_id
     *
     * @return the value of return_order_detail.market_place_id
     *
     * @mbggenerated
     */
    public String getMarket_place_id() {
        return market_place_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.market_place_id
     *
     * @param market_place_id the value for return_order_detail.market_place_id
     *
     * @mbggenerated
     */
    public void setMarket_place_id(String market_place_id) {
        this.market_place_id = market_place_id == null ? null : market_place_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.item_id
     *
     * @return the value of return_order_detail.item_id
     *
     * @mbggenerated
     */
    public String getItem_id() {
        return item_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.item_id
     *
     * @param item_id the value for return_order_detail.item_id
     *
     * @mbggenerated
     */
    public void setItem_id(String item_id) {
        this.item_id = item_id == null ? null : item_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.transaction_id
     *
     * @return the value of return_order_detail.transaction_id
     *
     * @mbggenerated
     */
    public String getTransaction_id() {
        return transaction_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.transaction_id
     *
     * @param transaction_id the value for return_order_detail.transaction_id
     *
     * @mbggenerated
     */
    public void setTransaction_id(String transaction_id) {
        this.transaction_id = transaction_id == null ? null : transaction_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.item_listing_site_id
     *
     * @return the value of return_order_detail.item_listing_site_id
     *
     * @mbggenerated
     */
    public Integer getItem_listing_site_id() {
        return item_listing_site_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.item_listing_site_id
     *
     * @param item_listing_site_id the value for return_order_detail.item_listing_site_id
     *
     * @mbggenerated
     */
    public void setItem_listing_site_id(Integer item_listing_site_id) {
        this.item_listing_site_id = item_listing_site_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.item_return_quantity
     *
     * @return the value of return_order_detail.item_return_quantity
     *
     * @mbggenerated
     */
    public Integer getItem_return_quantity() {
        return item_return_quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.item_return_quantity
     *
     * @param item_return_quantity the value for return_order_detail.item_return_quantity
     *
     * @mbggenerated
     */
    public void setItem_return_quantity(Integer item_return_quantity) {
        this.item_return_quantity = item_return_quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.item_title
     *
     * @return the value of return_order_detail.item_title
     *
     * @mbggenerated
     */
    public String getItem_title() {
        return item_title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.item_title
     *
     * @param item_title the value for return_order_detail.item_title
     *
     * @mbggenerated
     */
    public void setItem_title(String item_title) {
        this.item_title = item_title == null ? null : item_title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.item_pic_url
     *
     * @return the value of return_order_detail.item_pic_url
     *
     * @mbggenerated
     */
    public String getItem_pic_url() {
        return item_pic_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.item_pic_url
     *
     * @param item_pic_url the value for return_order_detail.item_pic_url
     *
     * @mbggenerated
     */
    public void setItem_pic_url(String item_pic_url) {
        this.item_pic_url = item_pic_url == null ? null : item_pic_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.item_transaction_date_value
     *
     * @return the value of return_order_detail.item_transaction_date_value
     *
     * @mbggenerated
     */
    public Date getItem_transaction_date_value() {
        return item_transaction_date_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.item_transaction_date_value
     *
     * @param item_transaction_date_value the value for return_order_detail.item_transaction_date_value
     *
     * @mbggenerated
     */
    public void setItem_transaction_date_value(Date item_transaction_date_value) {
        this.item_transaction_date_value = item_transaction_date_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.item_price_currency
     *
     * @return the value of return_order_detail.item_price_currency
     *
     * @mbggenerated
     */
    public String getItem_price_currency() {
        return item_price_currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.item_price_currency
     *
     * @param item_price_currency the value for return_order_detail.item_price_currency
     *
     * @mbggenerated
     */
    public void setItem_price_currency(String item_price_currency) {
        this.item_price_currency = item_price_currency == null ? null : item_price_currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.item_price_value
     *
     * @return the value of return_order_detail.item_price_value
     *
     * @mbggenerated
     */
    public Double getItem_price_value() {
        return item_price_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.item_price_value
     *
     * @param item_price_value the value for return_order_detail.item_price_value
     *
     * @mbggenerated
     */
    public void setItem_price_value(Double item_price_value) {
        this.item_price_value = item_price_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.item_ebay_plus_txn
     *
     * @return the value of return_order_detail.item_ebay_plus_txn
     *
     * @mbggenerated
     */
    public Boolean getItem_ebay_plus_txn() {
        return item_ebay_plus_txn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.item_ebay_plus_txn
     *
     * @param item_ebay_plus_txn the value for return_order_detail.item_ebay_plus_txn
     *
     * @mbggenerated
     */
    public void setItem_ebay_plus_txn(Boolean item_ebay_plus_txn) {
        this.item_ebay_plus_txn = item_ebay_plus_txn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.buyer_login_name
     *
     * @return the value of return_order_detail.buyer_login_name
     *
     * @mbggenerated
     */
    public String getBuyer_login_name() {
        return buyer_login_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.buyer_login_name
     *
     * @param buyer_login_name the value for return_order_detail.buyer_login_name
     *
     * @mbggenerated
     */
    public void setBuyer_login_name(String buyer_login_name) {
        this.buyer_login_name = buyer_login_name == null ? null : buyer_login_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.seller_login_name
     *
     * @return the value of return_order_detail.seller_login_name
     *
     * @mbggenerated
     */
    public String getSeller_login_name() {
        return seller_login_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.seller_login_name
     *
     * @param seller_login_name the value for return_order_detail.seller_login_name
     *
     * @mbggenerated
     */
    public void setSeller_login_name(String seller_login_name) {
        this.seller_login_name = seller_login_name == null ? null : seller_login_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.buyer_email_address
     *
     * @return the value of return_order_detail.buyer_email_address
     *
     * @mbggenerated
     */
    public String getBuyer_email_address() {
        return buyer_email_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.buyer_email_address
     *
     * @param buyer_email_address the value for return_order_detail.buyer_email_address
     *
     * @mbggenerated
     */
    public void setBuyer_email_address(String buyer_email_address) {
        this.buyer_email_address = buyer_email_address == null ? null : buyer_email_address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.seller_email_address
     *
     * @return the value of return_order_detail.seller_email_address
     *
     * @mbggenerated
     */
    public String getSeller_email_address() {
        return seller_email_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.seller_email_address
     *
     * @param seller_email_address the value for return_order_detail.seller_email_address
     *
     * @mbggenerated
     */
    public void setSeller_email_address(String seller_email_address) {
        this.seller_email_address = seller_email_address == null ? null : seller_email_address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.check_out_type
     *
     * @return the value of return_order_detail.check_out_type
     *
     * @mbggenerated
     */
    public String getCheck_out_type() {
        return check_out_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.check_out_type
     *
     * @param check_out_type the value for return_order_detail.check_out_type
     *
     * @mbggenerated
     */
    public void setCheck_out_type(String check_out_type) {
        this.check_out_type = check_out_type == null ? null : check_out_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.response_history
     *
     * @return the value of return_order_detail.response_history
     *
     * @mbggenerated
     */
    public String getResponse_history() {
        return response_history;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.response_history
     *
     * @param response_history the value for return_order_detail.response_history
     *
     * @mbggenerated
     */
    public void setResponse_history(String response_history) {
        this.response_history = response_history == null ? null : response_history.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.itemized_refund_details
     *
     * @return the value of return_order_detail.itemized_refund_details
     *
     * @mbggenerated
     */
    public String getItemized_refund_details() {
        return itemized_refund_details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.itemized_refund_details
     *
     * @param itemized_refund_details the value for return_order_detail.itemized_refund_details
     *
     * @mbggenerated
     */
    public void setItemized_refund_details(String itemized_refund_details) {
        this.itemized_refund_details = itemized_refund_details == null ? null : itemized_refund_details.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.is_rtn_shipping_editable
     *
     * @return the value of return_order_detail.is_rtn_shipping_editable
     *
     * @mbggenerated
     */
    public Boolean getIs_rtn_shipping_editable() {
        return is_rtn_shipping_editable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.is_rtn_shipping_editable
     *
     * @param is_rtn_shipping_editable the value for return_order_detail.is_rtn_shipping_editable
     *
     * @mbggenerated
     */
    public void setIs_rtn_shipping_editable(Boolean is_rtn_shipping_editable) {
        this.is_rtn_shipping_editable = is_rtn_shipping_editable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.actual_refund_detail_total_amount_value
     *
     * @return the value of return_order_detail.actual_refund_detail_total_amount_value
     *
     * @mbggenerated
     */
    public Double getActual_refund_detail_total_amount_value() {
        return actual_refund_detail_total_amount_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.actual_refund_detail_total_amount_value
     *
     * @param actual_refund_detail_total_amount_value the value for return_order_detail.actual_refund_detail_total_amount_value
     *
     * @mbggenerated
     */
    public void setActual_refund_detail_total_amount_value(Double actual_refund_detail_total_amount_value) {
        this.actual_refund_detail_total_amount_value = actual_refund_detail_total_amount_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.actual_refund_detail_total_amount_currency
     *
     * @return the value of return_order_detail.actual_refund_detail_total_amount_currency
     *
     * @mbggenerated
     */
    public String getActual_refund_detail_total_amount_currency() {
        return actual_refund_detail_total_amount_currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.actual_refund_detail_total_amount_currency
     *
     * @param actual_refund_detail_total_amount_currency the value for return_order_detail.actual_refund_detail_total_amount_currency
     *
     * @mbggenerated
     */
    public void setActual_refund_detail_total_amount_currency(String actual_refund_detail_total_amount_currency) {
        this.actual_refund_detail_total_amount_currency = actual_refund_detail_total_amount_currency == null ? null : actual_refund_detail_total_amount_currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.itemized_refund_detail
     *
     * @return the value of return_order_detail.itemized_refund_detail
     *
     * @mbggenerated
     */
    public String getItemized_refund_detail() {
        return itemized_refund_detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.itemized_refund_detail
     *
     * @param itemized_refund_detail the value for return_order_detail.itemized_refund_detail
     *
     * @mbggenerated
     */
    public void setItemized_refund_detail(String itemized_refund_detail) {
        this.itemized_refund_detail = itemized_refund_detail == null ? null : itemized_refund_detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.refund_status
     *
     * @return the value of return_order_detail.refund_status
     *
     * @mbggenerated
     */
    public String getRefund_status() {
        return refund_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.refund_status
     *
     * @param refund_status the value for return_order_detail.refund_status
     *
     * @mbggenerated
     */
    public void setRefund_status(String refund_status) {
        this.refund_status = refund_status == null ? null : refund_status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.refund_issued_date_value
     *
     * @return the value of return_order_detail.refund_issued_date_value
     *
     * @mbggenerated
     */
    public Date getRefund_issued_date_value() {
        return refund_issued_date_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.refund_issued_date_value
     *
     * @param refund_issued_date_value the value for return_order_detail.refund_issued_date_value
     *
     * @mbggenerated
     */
    public void setRefund_issued_date_value(Date refund_issued_date_value) {
        this.refund_issued_date_value = refund_issued_date_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.hold_creation_date_value
     *
     * @return the value of return_order_detail.hold_creation_date_value
     *
     * @mbggenerated
     */
    public Date getHold_creation_date_value() {
        return hold_creation_date_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.hold_creation_date_value
     *
     * @param hold_creation_date_value the value for return_order_detail.hold_creation_date_value
     *
     * @mbggenerated
     */
    public void setHold_creation_date_value(Date hold_creation_date_value) {
        this.hold_creation_date_value = hold_creation_date_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.hold_release_date_value
     *
     * @return the value of return_order_detail.hold_release_date_value
     *
     * @mbggenerated
     */
    public Date getHold_release_date_value() {
        return hold_release_date_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.hold_release_date_value
     *
     * @param hold_release_date_value the value for return_order_detail.hold_release_date_value
     *
     * @mbggenerated
     */
    public void setHold_release_date_value(Date hold_release_date_value) {
        this.hold_release_date_value = hold_release_date_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.hold_status
     *
     * @return the value of return_order_detail.hold_status
     *
     * @mbggenerated
     */
    public String getHold_status() {
        return hold_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.hold_status
     *
     * @param hold_status the value for return_order_detail.hold_status
     *
     * @mbggenerated
     */
    public void setHold_status(String hold_status) {
        this.hold_status = hold_status == null ? null : hold_status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.hold_reference_id
     *
     * @return the value of return_order_detail.hold_reference_id
     *
     * @mbggenerated
     */
    public String getHold_reference_id() {
        return hold_reference_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.hold_reference_id
     *
     * @param hold_reference_id the value for return_order_detail.hold_reference_id
     *
     * @mbggenerated
     */
    public void setHold_reference_id(String hold_reference_id) {
        this.hold_reference_id = hold_reference_id == null ? null : hold_reference_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.hold_transaction_id
     *
     * @return the value of return_order_detail.hold_transaction_id
     *
     * @mbggenerated
     */
    public String getHold_transaction_id() {
        return hold_transaction_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.hold_transaction_id
     *
     * @param hold_transaction_id the value for return_order_detail.hold_transaction_id
     *
     * @mbggenerated
     */
    public void setHold_transaction_id(String hold_transaction_id) {
        this.hold_transaction_id = hold_transaction_id == null ? null : hold_transaction_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.money_movement_info
     *
     * @return the value of return_order_detail.money_movement_info
     *
     * @mbggenerated
     */
    public String getMoney_movement_info() {
        return money_movement_info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.money_movement_info
     *
     * @param money_movement_info the value for return_order_detail.money_movement_info
     *
     * @mbggenerated
     */
    public void setMoney_movement_info(String money_movement_info) {
        this.money_movement_info = money_movement_info == null ? null : money_movement_info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.buyer_address_name
     *
     * @return the value of return_order_detail.buyer_address_name
     *
     * @mbggenerated
     */
    public String getBuyer_address_name() {
        return buyer_address_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.buyer_address_name
     *
     * @param buyer_address_name the value for return_order_detail.buyer_address_name
     *
     * @mbggenerated
     */
    public void setBuyer_address_name(String buyer_address_name) {
        this.buyer_address_name = buyer_address_name == null ? null : buyer_address_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.buyer_address_country
     *
     * @return the value of return_order_detail.buyer_address_country
     *
     * @mbggenerated
     */
    public String getBuyer_address_country() {
        return buyer_address_country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.buyer_address_country
     *
     * @param buyer_address_country the value for return_order_detail.buyer_address_country
     *
     * @mbggenerated
     */
    public void setBuyer_address_country(String buyer_address_country) {
        this.buyer_address_country = buyer_address_country == null ? null : buyer_address_country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.buyer_address_postal_code
     *
     * @return the value of return_order_detail.buyer_address_postal_code
     *
     * @mbggenerated
     */
    public String getBuyer_address_postal_code() {
        return buyer_address_postal_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.buyer_address_postal_code
     *
     * @param buyer_address_postal_code the value for return_order_detail.buyer_address_postal_code
     *
     * @mbggenerated
     */
    public void setBuyer_address_postal_code(String buyer_address_postal_code) {
        this.buyer_address_postal_code = buyer_address_postal_code == null ? null : buyer_address_postal_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.buyer_address_state_or_province
     *
     * @return the value of return_order_detail.buyer_address_state_or_province
     *
     * @mbggenerated
     */
    public String getBuyer_address_state_or_province() {
        return buyer_address_state_or_province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.buyer_address_state_or_province
     *
     * @param buyer_address_state_or_province the value for return_order_detail.buyer_address_state_or_province
     *
     * @mbggenerated
     */
    public void setBuyer_address_state_or_province(String buyer_address_state_or_province) {
        this.buyer_address_state_or_province = buyer_address_state_or_province == null ? null : buyer_address_state_or_province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.buyer_address_city
     *
     * @return the value of return_order_detail.buyer_address_city
     *
     * @mbggenerated
     */
    public String getBuyer_address_city() {
        return buyer_address_city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.buyer_address_city
     *
     * @param buyer_address_city the value for return_order_detail.buyer_address_city
     *
     * @mbggenerated
     */
    public void setBuyer_address_city(String buyer_address_city) {
        this.buyer_address_city = buyer_address_city == null ? null : buyer_address_city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.buyer_address_address_line1
     *
     * @return the value of return_order_detail.buyer_address_address_line1
     *
     * @mbggenerated
     */
    public String getBuyer_address_address_line1() {
        return buyer_address_address_line1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.buyer_address_address_line1
     *
     * @param buyer_address_address_line1 the value for return_order_detail.buyer_address_address_line1
     *
     * @mbggenerated
     */
    public void setBuyer_address_address_line1(String buyer_address_address_line1) {
        this.buyer_address_address_line1 = buyer_address_address_line1 == null ? null : buyer_address_address_line1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.buyer_address_address_line2
     *
     * @return the value of return_order_detail.buyer_address_address_line2
     *
     * @mbggenerated
     */
    public String getBuyer_address_address_line2() {
        return buyer_address_address_line2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.buyer_address_address_line2
     *
     * @param buyer_address_address_line2 the value for return_order_detail.buyer_address_address_line2
     *
     * @mbggenerated
     */
    public void setBuyer_address_address_line2(String buyer_address_address_line2) {
        this.buyer_address_address_line2 = buyer_address_address_line2 == null ? null : buyer_address_address_line2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.seller_address_name
     *
     * @return the value of return_order_detail.seller_address_name
     *
     * @mbggenerated
     */
    public String getSeller_address_name() {
        return seller_address_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.seller_address_name
     *
     * @param seller_address_name the value for return_order_detail.seller_address_name
     *
     * @mbggenerated
     */
    public void setSeller_address_name(String seller_address_name) {
        this.seller_address_name = seller_address_name == null ? null : seller_address_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.seller_address_country
     *
     * @return the value of return_order_detail.seller_address_country
     *
     * @mbggenerated
     */
    public String getSeller_address_country() {
        return seller_address_country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.seller_address_country
     *
     * @param seller_address_country the value for return_order_detail.seller_address_country
     *
     * @mbggenerated
     */
    public void setSeller_address_country(String seller_address_country) {
        this.seller_address_country = seller_address_country == null ? null : seller_address_country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.seller_address_postal_code
     *
     * @return the value of return_order_detail.seller_address_postal_code
     *
     * @mbggenerated
     */
    public String getSeller_address_postal_code() {
        return seller_address_postal_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.seller_address_postal_code
     *
     * @param seller_address_postal_code the value for return_order_detail.seller_address_postal_code
     *
     * @mbggenerated
     */
    public void setSeller_address_postal_code(String seller_address_postal_code) {
        this.seller_address_postal_code = seller_address_postal_code == null ? null : seller_address_postal_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.seller_address_state_or_province
     *
     * @return the value of return_order_detail.seller_address_state_or_province
     *
     * @mbggenerated
     */
    public String getSeller_address_state_or_province() {
        return seller_address_state_or_province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.seller_address_state_or_province
     *
     * @param seller_address_state_or_province the value for return_order_detail.seller_address_state_or_province
     *
     * @mbggenerated
     */
    public void setSeller_address_state_or_province(String seller_address_state_or_province) {
        this.seller_address_state_or_province = seller_address_state_or_province == null ? null : seller_address_state_or_province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.seller_address_city
     *
     * @return the value of return_order_detail.seller_address_city
     *
     * @mbggenerated
     */
    public String getSeller_address_city() {
        return seller_address_city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.seller_address_city
     *
     * @param seller_address_city the value for return_order_detail.seller_address_city
     *
     * @mbggenerated
     */
    public void setSeller_address_city(String seller_address_city) {
        this.seller_address_city = seller_address_city == null ? null : seller_address_city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.seller_address_address_line1
     *
     * @return the value of return_order_detail.seller_address_address_line1
     *
     * @mbggenerated
     */
    public String getSeller_address_address_line1() {
        return seller_address_address_line1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.seller_address_address_line1
     *
     * @param seller_address_address_line1 the value for return_order_detail.seller_address_address_line1
     *
     * @mbggenerated
     */
    public void setSeller_address_address_line1(String seller_address_address_line1) {
        this.seller_address_address_line1 = seller_address_address_line1 == null ? null : seller_address_address_line1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.seller_address_address_line2
     *
     * @return the value of return_order_detail.seller_address_address_line2
     *
     * @mbggenerated
     */
    public String getSeller_address_address_line2() {
        return seller_address_address_line2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.seller_address_address_line2
     *
     * @param seller_address_address_line2 the value for return_order_detail.seller_address_address_line2
     *
     * @mbggenerated
     */
    public void setSeller_address_address_line2(String seller_address_address_line2) {
        this.seller_address_address_line2 = seller_address_address_line2 == null ? null : seller_address_address_line2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.return_shipment_info_shipping_method
     *
     * @return the value of return_order_detail.return_shipment_info_shipping_method
     *
     * @mbggenerated
     */
    public String getReturn_shipment_info_shipping_method() {
        return return_shipment_info_shipping_method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.return_shipment_info_shipping_method
     *
     * @param return_shipment_info_shipping_method the value for return_order_detail.return_shipment_info_shipping_method
     *
     * @mbggenerated
     */
    public void setReturn_shipment_info_shipping_method(String return_shipment_info_shipping_method) {
        this.return_shipment_info_shipping_method = return_shipment_info_shipping_method == null ? null : return_shipment_info_shipping_method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.return_shipment_shipped_by
     *
     * @return the value of return_order_detail.return_shipment_shipped_by
     *
     * @mbggenerated
     */
    public String getReturn_shipment_shipped_by() {
        return return_shipment_shipped_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.return_shipment_shipped_by
     *
     * @param return_shipment_shipped_by the value for return_order_detail.return_shipment_shipped_by
     *
     * @mbggenerated
     */
    public void setReturn_shipment_shipped_by(String return_shipment_shipped_by) {
        this.return_shipment_shipped_by = return_shipment_shipped_by == null ? null : return_shipment_shipped_by.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.return_shipment_carrier_id
     *
     * @return the value of return_order_detail.return_shipment_carrier_id
     *
     * @mbggenerated
     */
    public Integer getReturn_shipment_carrier_id() {
        return return_shipment_carrier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.return_shipment_carrier_id
     *
     * @param return_shipment_carrier_id the value for return_order_detail.return_shipment_carrier_id
     *
     * @mbggenerated
     */
    public void setReturn_shipment_carrier_id(Integer return_shipment_carrier_id) {
        this.return_shipment_carrier_id = return_shipment_carrier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.return_shipment_carrier_enum
     *
     * @return the value of return_order_detail.return_shipment_carrier_enum
     *
     * @mbggenerated
     */
    public String getReturn_shipment_carrier_enum() {
        return return_shipment_carrier_enum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.return_shipment_carrier_enum
     *
     * @param return_shipment_carrier_enum the value for return_order_detail.return_shipment_carrier_enum
     *
     * @mbggenerated
     */
    public void setReturn_shipment_carrier_enum(String return_shipment_carrier_enum) {
        this.return_shipment_carrier_enum = return_shipment_carrier_enum == null ? null : return_shipment_carrier_enum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.return_shipment_carrier_name
     *
     * @return the value of return_order_detail.return_shipment_carrier_name
     *
     * @mbggenerated
     */
    public String getReturn_shipment_carrier_name() {
        return return_shipment_carrier_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.return_shipment_carrier_name
     *
     * @param return_shipment_carrier_name the value for return_order_detail.return_shipment_carrier_name
     *
     * @mbggenerated
     */
    public void setReturn_shipment_carrier_name(String return_shipment_carrier_name) {
        this.return_shipment_carrier_name = return_shipment_carrier_name == null ? null : return_shipment_carrier_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.return_shipment_carrier_used
     *
     * @return the value of return_order_detail.return_shipment_carrier_used
     *
     * @mbggenerated
     */
    public String getReturn_shipment_carrier_used() {
        return return_shipment_carrier_used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.return_shipment_carrier_used
     *
     * @param return_shipment_carrier_used the value for return_order_detail.return_shipment_carrier_used
     *
     * @mbggenerated
     */
    public void setReturn_shipment_carrier_used(String return_shipment_carrier_used) {
        this.return_shipment_carrier_used = return_shipment_carrier_used == null ? null : return_shipment_carrier_used.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.return_shipment_delivery_status
     *
     * @return the value of return_order_detail.return_shipment_delivery_status
     *
     * @mbggenerated
     */
    public String getReturn_shipment_delivery_status() {
        return return_shipment_delivery_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.return_shipment_delivery_status
     *
     * @param return_shipment_delivery_status the value for return_order_detail.return_shipment_delivery_status
     *
     * @mbggenerated
     */
    public void setReturn_shipment_delivery_status(String return_shipment_delivery_status) {
        this.return_shipment_delivery_status = return_shipment_delivery_status == null ? null : return_shipment_delivery_status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.return_shipment_destination_address_name
     *
     * @return the value of return_order_detail.return_shipment_destination_address_name
     *
     * @mbggenerated
     */
    public String getReturn_shipment_destination_address_name() {
        return return_shipment_destination_address_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.return_shipment_destination_address_name
     *
     * @param return_shipment_destination_address_name the value for return_order_detail.return_shipment_destination_address_name
     *
     * @mbggenerated
     */
    public void setReturn_shipment_destination_address_name(String return_shipment_destination_address_name) {
        this.return_shipment_destination_address_name = return_shipment_destination_address_name == null ? null : return_shipment_destination_address_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.return_shipment_destination_address_country
     *
     * @return the value of return_order_detail.return_shipment_destination_address_country
     *
     * @mbggenerated
     */
    public String getReturn_shipment_destination_address_country() {
        return return_shipment_destination_address_country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.return_shipment_destination_address_country
     *
     * @param return_shipment_destination_address_country the value for return_order_detail.return_shipment_destination_address_country
     *
     * @mbggenerated
     */
    public void setReturn_shipment_destination_address_country(String return_shipment_destination_address_country) {
        this.return_shipment_destination_address_country = return_shipment_destination_address_country == null ? null : return_shipment_destination_address_country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.return_shipment_destination_address_postal_code
     *
     * @return the value of return_order_detail.return_shipment_destination_address_postal_code
     *
     * @mbggenerated
     */
    public String getReturn_shipment_destination_address_postal_code() {
        return return_shipment_destination_address_postal_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.return_shipment_destination_address_postal_code
     *
     * @param return_shipment_destination_address_postal_code the value for return_order_detail.return_shipment_destination_address_postal_code
     *
     * @mbggenerated
     */
    public void setReturn_shipment_destination_address_postal_code(String return_shipment_destination_address_postal_code) {
        this.return_shipment_destination_address_postal_code = return_shipment_destination_address_postal_code == null ? null : return_shipment_destination_address_postal_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.return_shipment_destination_address_state_or_province
     *
     * @return the value of return_order_detail.return_shipment_destination_address_state_or_province
     *
     * @mbggenerated
     */
    public String getReturn_shipment_destination_address_state_or_province() {
        return return_shipment_destination_address_state_or_province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.return_shipment_destination_address_state_or_province
     *
     * @param return_shipment_destination_address_state_or_province the value for return_order_detail.return_shipment_destination_address_state_or_province
     *
     * @mbggenerated
     */
    public void setReturn_shipment_destination_address_state_or_province(String return_shipment_destination_address_state_or_province) {
        this.return_shipment_destination_address_state_or_province = return_shipment_destination_address_state_or_province == null ? null : return_shipment_destination_address_state_or_province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.return_shipment_destination_address_city
     *
     * @return the value of return_order_detail.return_shipment_destination_address_city
     *
     * @mbggenerated
     */
    public String getReturn_shipment_destination_address_city() {
        return return_shipment_destination_address_city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.return_shipment_destination_address_city
     *
     * @param return_shipment_destination_address_city the value for return_order_detail.return_shipment_destination_address_city
     *
     * @mbggenerated
     */
    public void setReturn_shipment_destination_address_city(String return_shipment_destination_address_city) {
        this.return_shipment_destination_address_city = return_shipment_destination_address_city == null ? null : return_shipment_destination_address_city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.return_shipment_destination_address__line1
     *
     * @return the value of return_order_detail.return_shipment_destination_address__line1
     *
     * @mbggenerated
     */
    public String getReturn_shipment_destination_address__line1() {
        return return_shipment_destination_address__line1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.return_shipment_destination_address__line1
     *
     * @param return_shipment_destination_address__line1 the value for return_order_detail.return_shipment_destination_address__line1
     *
     * @mbggenerated
     */
    public void setReturn_shipment_destination_address__line1(String return_shipment_destination_address__line1) {
        this.return_shipment_destination_address__line1 = return_shipment_destination_address__line1 == null ? null : return_shipment_destination_address__line1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.return_shipment_destination_address__line2
     *
     * @return the value of return_order_detail.return_shipment_destination_address__line2
     *
     * @mbggenerated
     */
    public String getReturn_shipment_destination_address__line2() {
        return return_shipment_destination_address__line2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.return_shipment_destination_address__line2
     *
     * @param return_shipment_destination_address__line2 the value for return_order_detail.return_shipment_destination_address__line2
     *
     * @mbggenerated
     */
    public void setReturn_shipment_destination_address__line2(String return_shipment_destination_address__line2) {
        this.return_shipment_destination_address__line2 = return_shipment_destination_address__line2 == null ? null : return_shipment_destination_address__line2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.return_shipment_origin_address_name
     *
     * @return the value of return_order_detail.return_shipment_origin_address_name
     *
     * @mbggenerated
     */
    public String getReturn_shipment_origin_address_name() {
        return return_shipment_origin_address_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.return_shipment_origin_address_name
     *
     * @param return_shipment_origin_address_name the value for return_order_detail.return_shipment_origin_address_name
     *
     * @mbggenerated
     */
    public void setReturn_shipment_origin_address_name(String return_shipment_origin_address_name) {
        this.return_shipment_origin_address_name = return_shipment_origin_address_name == null ? null : return_shipment_origin_address_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.return_shipment_origin_address_country
     *
     * @return the value of return_order_detail.return_shipment_origin_address_country
     *
     * @mbggenerated
     */
    public String getReturn_shipment_origin_address_country() {
        return return_shipment_origin_address_country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.return_shipment_origin_address_country
     *
     * @param return_shipment_origin_address_country the value for return_order_detail.return_shipment_origin_address_country
     *
     * @mbggenerated
     */
    public void setReturn_shipment_origin_address_country(String return_shipment_origin_address_country) {
        this.return_shipment_origin_address_country = return_shipment_origin_address_country == null ? null : return_shipment_origin_address_country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.return_shipment_origin_address_postal_code
     *
     * @return the value of return_order_detail.return_shipment_origin_address_postal_code
     *
     * @mbggenerated
     */
    public String getReturn_shipment_origin_address_postal_code() {
        return return_shipment_origin_address_postal_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.return_shipment_origin_address_postal_code
     *
     * @param return_shipment_origin_address_postal_code the value for return_order_detail.return_shipment_origin_address_postal_code
     *
     * @mbggenerated
     */
    public void setReturn_shipment_origin_address_postal_code(String return_shipment_origin_address_postal_code) {
        this.return_shipment_origin_address_postal_code = return_shipment_origin_address_postal_code == null ? null : return_shipment_origin_address_postal_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.return_shipment_origin_address_state_or_province
     *
     * @return the value of return_order_detail.return_shipment_origin_address_state_or_province
     *
     * @mbggenerated
     */
    public String getReturn_shipment_origin_address_state_or_province() {
        return return_shipment_origin_address_state_or_province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.return_shipment_origin_address_state_or_province
     *
     * @param return_shipment_origin_address_state_or_province the value for return_order_detail.return_shipment_origin_address_state_or_province
     *
     * @mbggenerated
     */
    public void setReturn_shipment_origin_address_state_or_province(String return_shipment_origin_address_state_or_province) {
        this.return_shipment_origin_address_state_or_province = return_shipment_origin_address_state_or_province == null ? null : return_shipment_origin_address_state_or_province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.return_shipment_origin_address_city
     *
     * @return the value of return_order_detail.return_shipment_origin_address_city
     *
     * @mbggenerated
     */
    public String getReturn_shipment_origin_address_city() {
        return return_shipment_origin_address_city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.return_shipment_origin_address_city
     *
     * @param return_shipment_origin_address_city the value for return_order_detail.return_shipment_origin_address_city
     *
     * @mbggenerated
     */
    public void setReturn_shipment_origin_address_city(String return_shipment_origin_address_city) {
        this.return_shipment_origin_address_city = return_shipment_origin_address_city == null ? null : return_shipment_origin_address_city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.return_shipment_origin_address_line1
     *
     * @return the value of return_order_detail.return_shipment_origin_address_line1
     *
     * @mbggenerated
     */
    public String getReturn_shipment_origin_address_line1() {
        return return_shipment_origin_address_line1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.return_shipment_origin_address_line1
     *
     * @param return_shipment_origin_address_line1 the value for return_order_detail.return_shipment_origin_address_line1
     *
     * @mbggenerated
     */
    public void setReturn_shipment_origin_address_line1(String return_shipment_origin_address_line1) {
        this.return_shipment_origin_address_line1 = return_shipment_origin_address_line1 == null ? null : return_shipment_origin_address_line1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.return_shipment_origin_address_line2
     *
     * @return the value of return_order_detail.return_shipment_origin_address_line2
     *
     * @mbggenerated
     */
    public String getReturn_shipment_origin_address_line2() {
        return return_shipment_origin_address_line2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.return_shipment_origin_address_line2
     *
     * @param return_shipment_origin_address_line2 the value for return_order_detail.return_shipment_origin_address_line2
     *
     * @mbggenerated
     */
    public void setReturn_shipment_origin_address_line2(String return_shipment_origin_address_line2) {
        this.return_shipment_origin_address_line2 = return_shipment_origin_address_line2 == null ? null : return_shipment_origin_address_line2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.return_shipment_mark_as_received
     *
     * @return the value of return_order_detail.return_shipment_mark_as_received
     *
     * @mbggenerated
     */
    public Boolean getReturn_shipment_mark_as_received() {
        return return_shipment_mark_as_received;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.return_shipment_mark_as_received
     *
     * @param return_shipment_mark_as_received the value for return_order_detail.return_shipment_mark_as_received
     *
     * @mbggenerated
     */
    public void setReturn_shipment_mark_as_received(Boolean return_shipment_mark_as_received) {
        this.return_shipment_mark_as_received = return_shipment_mark_as_received;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.return_shipment_active
     *
     * @return the value of return_order_detail.return_shipment_active
     *
     * @mbggenerated
     */
    public Boolean getReturn_shipment_active() {
        return return_shipment_active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.return_shipment_active
     *
     * @param return_shipment_active the value for return_order_detail.return_shipment_active
     *
     * @mbggenerated
     */
    public void setReturn_shipment_active(Boolean return_shipment_active) {
        this.return_shipment_active = return_shipment_active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.return_shipment_label_print_expired
     *
     * @return the value of return_order_detail.return_shipment_label_print_expired
     *
     * @mbggenerated
     */
    public Boolean getReturn_shipment_label_print_expired() {
        return return_shipment_label_print_expired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.return_shipment_label_print_expired
     *
     * @param return_shipment_label_print_expired the value for return_order_detail.return_shipment_label_print_expired
     *
     * @mbggenerated
     */
    public void setReturn_shipment_label_print_expired(Boolean return_shipment_label_print_expired) {
        this.return_shipment_label_print_expired = return_shipment_label_print_expired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.return_shipment_label_void_expired
     *
     * @return the value of return_order_detail.return_shipment_label_void_expired
     *
     * @mbggenerated
     */
    public Boolean getReturn_shipment_label_void_expired() {
        return return_shipment_label_void_expired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.return_shipment_label_void_expired
     *
     * @param return_shipment_label_void_expired the value for return_order_detail.return_shipment_label_void_expired
     *
     * @mbggenerated
     */
    public void setReturn_shipment_label_void_expired(Boolean return_shipment_label_void_expired) {
        this.return_shipment_label_void_expired = return_shipment_label_void_expired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.shipping_label_cost_total_amount_value
     *
     * @return the value of return_order_detail.shipping_label_cost_total_amount_value
     *
     * @mbggenerated
     */
    public Double getShipping_label_cost_total_amount_value() {
        return shipping_label_cost_total_amount_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.shipping_label_cost_total_amount_value
     *
     * @param shipping_label_cost_total_amount_value the value for return_order_detail.shipping_label_cost_total_amount_value
     *
     * @mbggenerated
     */
    public void setShipping_label_cost_total_amount_value(Double shipping_label_cost_total_amount_value) {
        this.shipping_label_cost_total_amount_value = shipping_label_cost_total_amount_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.shipping_label_cost_total_amount_currency
     *
     * @return the value of return_order_detail.shipping_label_cost_total_amount_currency
     *
     * @mbggenerated
     */
    public String getShipping_label_cost_total_amount_currency() {
        return shipping_label_cost_total_amount_currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.shipping_label_cost_total_amount_currency
     *
     * @param shipping_label_cost_total_amount_currency the value for return_order_detail.shipping_label_cost_total_amount_currency
     *
     * @mbggenerated
     */
    public void setShipping_label_cost_total_amount_currency(String shipping_label_cost_total_amount_currency) {
        this.shipping_label_cost_total_amount_currency = shipping_label_cost_total_amount_currency == null ? null : shipping_label_cost_total_amount_currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.itemized_return_shipping_cost
     *
     * @return the value of return_order_detail.itemized_return_shipping_cost
     *
     * @mbggenerated
     */
    public String getItemized_return_shipping_cost() {
        return itemized_return_shipping_cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.itemized_return_shipping_cost
     *
     * @param itemized_return_shipping_cost the value for return_order_detail.itemized_return_shipping_cost
     *
     * @mbggenerated
     */
    public void setItemized_return_shipping_cost(String itemized_return_shipping_cost) {
        this.itemized_return_shipping_cost = itemized_return_shipping_cost == null ? null : itemized_return_shipping_cost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.payee
     *
     * @return the value of return_order_detail.payee
     *
     * @mbggenerated
     */
    public String getPayee() {
        return payee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.payee
     *
     * @param payee the value for return_order_detail.payee
     *
     * @mbggenerated
     */
    public void setPayee(String payee) {
        this.payee = payee == null ? null : payee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.all_shipment_trackings
     *
     * @return the value of return_order_detail.all_shipment_trackings
     *
     * @mbggenerated
     */
    public String getAll_shipment_trackings() {
        return all_shipment_trackings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.all_shipment_trackings
     *
     * @param all_shipment_trackings the value for return_order_detail.all_shipment_trackings
     *
     * @mbggenerated
     */
    public void setAll_shipment_trackings(String all_shipment_trackings) {
        this.all_shipment_trackings = all_shipment_trackings == null ? null : all_shipment_trackings.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.return_close_reason
     *
     * @return the value of return_order_detail.return_close_reason
     *
     * @mbggenerated
     */
    public String getReturn_close_reason() {
        return return_close_reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.return_close_reason
     *
     * @param return_close_reason the value for return_order_detail.return_close_reason
     *
     * @mbggenerated
     */
    public void setReturn_close_reason(String return_close_reason) {
        this.return_close_reason = return_close_reason == null ? null : return_close_reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_detail.buyer_close_reason
     *
     * @return the value of return_order_detail.buyer_close_reason
     *
     * @mbggenerated
     */
    public String getBuyer_close_reason() {
        return buyer_close_reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_detail.buyer_close_reason
     *
     * @param buyer_close_reason the value for return_order_detail.buyer_close_reason
     *
     * @mbggenerated
     */
    public void setBuyer_close_reason(String buyer_close_reason) {
        this.buyer_close_reason = buyer_close_reason == null ? null : buyer_close_reason.trim();
    }
}