package entity.returnsummary;

import java.io.Serializable;
import java.util.Date;

public class ReturnOrderList implements Serializable {
  
    private String return_id;

   
    private Integer user_id;

    private Integer shop_id;

   
    private String buyer_login_name;

    
    private String seller_login_name;

    private String current_type;

    private String state;

    private String status;

    private String creation_info_item_id;

    private String creation_info_transaction_id;

    
    private Integer creation_info_return_quantity;

    private String creation_info_item_title;

    private String creation_info_type;

    private String creation_info_reason;

    private String creation_info_reason_type;

    private String creation_info_comments_content;

   
    private Date creation_info_creation_date_value;

    private Double seller_total_estimated_refund_amount_value;

    private String seller_total_estimated_refund_amount_currency;

    private Double seller_total_actual_refund_amount_value;

    private String seller_total_actual_refund_amount_currency;

    private Double buyer_total_estimated_refund_amount_value;

    private String buyer_total_estimated_refund_amount_currency;

    private Double buyer_total_actual_refund_amount_value;

    private String buyer_total_refund_actual_refund_amount_currency;

    private String seller_response_due_activity_due;

    private Date seller_response_due_respond_by_date_value;

    private String buyer_response_due_activity_due;

   
    private Date buyer_response_due_respond_by_date_value;

    
    private Date buyer_escalation_eligibility_info_start_time;

    private Date buyer_escalation_eligibility_info_end_time;

   
    private Boolean buyer_escalation_eligibility_info_eligible;

    private Date seller_escalation_eligibility_Info_start_time;

    private Date seller_escalation_eligibility_Info_end_time;

   
    private Boolean seller_escalation_eligibility_info_eligible;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order_list.seller_available_options
     *
     * @mbggenerated
     */
    private String seller_available_options;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order_list.buyer_available_options
     *
     * @mbggenerated
     */
    private String buyer_available_options;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order_list.return_policy_multiple_return_address
     *
     * @mbggenerated
     */
    private Boolean return_policy_multiple_return_address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order_list.return_policy_rmarequired
     *
     * @mbggenerated
     */
    private Boolean return_policy_rmarequired;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order_list.flags
     *
     * @mbggenerated
     */
    private String flags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column return_order_list.timeout_date_value
     *
     * @mbggenerated
     */
    private Date timeout_date_value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table return_order_list
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.returnId
     *
     * @return the value of return_order_list.returnId
     *
     * @mbggenerated
     */
    public String getReturn_id() {
        return return_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.returnId
     *
     * @param returnId the value for return_order_list.returnId
     *
     * @mbggenerated
     */
    public void setReturnId(String return_id) {
        this.return_id = return_id == null ? null : return_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.user_id
     *
     * @return the value of return_order_list.user_id
     *
     * @mbggenerated
     */
    public Integer getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.user_id
     *
     * @param user_id the value for return_order_list.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.shop_id
     *
     * @return the value of return_order_list.shop_id
     *
     * @mbggenerated
     */
    public Integer getShop_id() {
        return shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.shop_id
     *
     * @param shop_id the value for return_order_list.shop_id
     *
     * @mbggenerated
     */
    public void setShop_id(Integer shop_id) {
        this.shop_id = shop_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.buyer_login_name
     *
     * @return the value of return_order_list.buyer_login_name
     *
     * @mbggenerated
     */
    public String getBuyer_login_name() {
        return buyer_login_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.buyer_login_name
     *
     * @param buyer_login_name the value for return_order_list.buyer_login_name
     *
     * @mbggenerated
     */
    public void setBuyer_login_name(String buyer_login_name) {
        this.buyer_login_name = buyer_login_name == null ? null : buyer_login_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.seller_login_name
     *
     * @return the value of return_order_list.seller_login_name
     *
     * @mbggenerated
     */
    public String getSeller_login_name() {
        return seller_login_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.seller_login_name
     *
     * @param seller_login_name the value for return_order_list.seller_login_name
     *
     * @mbggenerated
     */
    public void setSeller_login_name(String seller_login_name) {
        this.seller_login_name = seller_login_name == null ? null : seller_login_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.current_type
     *
     * @return the value of return_order_list.current_type
     *
     * @mbggenerated
     */
    public String getCurrent_type() {
        return current_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.current_type
     *
     * @param current_type the value for return_order_list.current_type
     *
     * @mbggenerated
     */
    public void setCurrent_type(String current_type) {
        this.current_type = current_type == null ? null : current_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.state
     *
     * @return the value of return_order_list.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.state
     *
     * @param state the value for return_order_list.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.status
     *
     * @return the value of return_order_list.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.status
     *
     * @param status the value for return_order_list.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.creation_info_item_id
     *
     * @return the value of return_order_list.creation_info_item_id
     *
     * @mbggenerated
     */
    public String getCreation_info_item_id() {
        return creation_info_item_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.creation_info_item_id
     *
     * @param creation_info_item_id the value for return_order_list.creation_info_item_id
     *
     * @mbggenerated
     */
    public void setCreation_info_item_id(String creation_info_item_id) {
        this.creation_info_item_id = creation_info_item_id == null ? null : creation_info_item_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.creation_info_transaction_id
     *
     * @return the value of return_order_list.creation_info_transaction_id
     *
     * @mbggenerated
     */
    public String getCreation_info_transaction_id() {
        return creation_info_transaction_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.creation_info_transaction_id
     *
     * @param creation_info_transaction_id the value for return_order_list.creation_info_transaction_id
     *
     * @mbggenerated
     */
    public void setCreation_info_transaction_id(String creation_info_transaction_id) {
        this.creation_info_transaction_id = creation_info_transaction_id == null ? null : creation_info_transaction_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.creation_info_return_quantity
     *
     * @return the value of return_order_list.creation_info_return_quantity
     *
     * @mbggenerated
     */
    public Integer getCreation_info_return_quantity() {
        return creation_info_return_quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.creation_info_return_quantity
     *
     * @param creation_info_return_quantity the value for return_order_list.creation_info_return_quantity
     *
     * @mbggenerated
     */
    public void setCreation_info_return_quantity(Integer creation_info_return_quantity) {
        this.creation_info_return_quantity = creation_info_return_quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.creation_info_item_title
     *
     * @return the value of return_order_list.creation_info_item_title
     *
     * @mbggenerated
     */
    public String getCreation_info_item_title() {
        return creation_info_item_title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.creation_info_item_title
     *
     * @param creation_info_item_title the value for return_order_list.creation_info_item_title
     *
     * @mbggenerated
     */
    public void setCreation_info_item_title(String creation_info_item_title) {
        this.creation_info_item_title = creation_info_item_title == null ? null : creation_info_item_title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.creation_info_type
     *
     * @return the value of return_order_list.creation_info_type
     *
     * @mbggenerated
     */
    public String getCreation_info_type() {
        return creation_info_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.creation_info_type
     *
     * @param creation_info_type the value for return_order_list.creation_info_type
     *
     * @mbggenerated
     */
    public void setCreation_info_type(String creation_info_type) {
        this.creation_info_type = creation_info_type == null ? null : creation_info_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.creation_info_reason
     *
     * @return the value of return_order_list.creation_info_reason
     *
     * @mbggenerated
     */
    public String getCreation_info_reason() {
        return creation_info_reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.creation_info_reason
     *
     * @param creation_info_reason the value for return_order_list.creation_info_reason
     *
     * @mbggenerated
     */
    public void setCreation_info_reason(String creation_info_reason) {
        this.creation_info_reason = creation_info_reason == null ? null : creation_info_reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.creation_info_reason_type
     *
     * @return the value of return_order_list.creation_info_reason_type
     *
     * @mbggenerated
     */
    public String getCreation_info_reason_type() {
        return creation_info_reason_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.creation_info_reason_type
     *
     * @param creation_info_reason_type the value for return_order_list.creation_info_reason_type
     *
     * @mbggenerated
     */
    public void setCreation_info_reason_type(String creation_info_reason_type) {
        this.creation_info_reason_type = creation_info_reason_type == null ? null : creation_info_reason_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.creation_info_comments_content
     *
     * @return the value of return_order_list.creation_info_comments_content
     *
     * @mbggenerated
     */
    public String getCreation_info_comments_content() {
        return creation_info_comments_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.creation_info_comments_content
     *
     * @param creation_info_comments_content the value for return_order_list.creation_info_comments_content
     *
     * @mbggenerated
     */
    public void setCreation_info_comments_content(String creation_info_comments_content) {
        this.creation_info_comments_content = creation_info_comments_content == null ? null : creation_info_comments_content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.creation_info_creation_date_value
     *
     * @return the value of return_order_list.creation_info_creation_date_value
     *
     * @mbggenerated
     */
    public Date getCreation_info_creation_date_value() {
        return creation_info_creation_date_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.creation_info_creation_date_value
     *
     * @param creation_info_creation_date_value the value for return_order_list.creation_info_creation_date_value
     *
     * @mbggenerated
     */
    public void setCreation_info_creation_date_value(Date creation_info_creation_date_value) {
        this.creation_info_creation_date_value = creation_info_creation_date_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.seller_total_estimated_refund_amount_value
     *
     * @return the value of return_order_list.seller_total_estimated_refund_amount_value
     *
     * @mbggenerated
     */
    public Double getSeller_total_estimated_refund_amount_value() {
        return seller_total_estimated_refund_amount_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.seller_total_estimated_refund_amount_value
     *
     * @param seller_total_estimated_refund_amount_value the value for return_order_list.seller_total_estimated_refund_amount_value
     *
     * @mbggenerated
     */
    public void setSeller_total_estimated_refund_amount_value(Double seller_total_estimated_refund_amount_value) {
        this.seller_total_estimated_refund_amount_value = seller_total_estimated_refund_amount_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.seller_total_estimated_refund_amount_currency
     *
     * @return the value of return_order_list.seller_total_estimated_refund_amount_currency
     *
     * @mbggenerated
     */
    public String getSeller_total_estimated_refund_amount_currency() {
        return seller_total_estimated_refund_amount_currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.seller_total_estimated_refund_amount_currency
     *
     * @param seller_total_estimated_refund_amount_currency the value for return_order_list.seller_total_estimated_refund_amount_currency
     *
     * @mbggenerated
     */
    public void setSeller_total_estimated_refund_amount_currency(String seller_total_estimated_refund_amount_currency) {
        this.seller_total_estimated_refund_amount_currency = seller_total_estimated_refund_amount_currency == null ? null : seller_total_estimated_refund_amount_currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.seller_total_actual_refund_amount_value
     *
     * @return the value of return_order_list.seller_total_actual_refund_amount_value
     *
     * @mbggenerated
     */
    public Double getSeller_total_actual_refund_amount_value() {
        return seller_total_actual_refund_amount_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.seller_total_actual_refund_amount_value
     *
     * @param seller_total_actual_refund_amount_value the value for return_order_list.seller_total_actual_refund_amount_value
     *
     * @mbggenerated
     */
    public void setSeller_total_actual_refund_amount_value(Double seller_total_actual_refund_amount_value) {
        this.seller_total_actual_refund_amount_value = seller_total_actual_refund_amount_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.seller_total_actual_refund_amount_currency
     *
     * @return the value of return_order_list.seller_total_actual_refund_amount_currency
     *
     * @mbggenerated
     */
    public String getSeller_total_actual_refund_amount_currency() {
        return seller_total_actual_refund_amount_currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.seller_total_actual_refund_amount_currency
     *
     * @param seller_total_actual_refund_amount_currency the value for return_order_list.seller_total_actual_refund_amount_currency
     *
     * @mbggenerated
     */
    public void setSeller_total_actual_refund_amount_currency(String seller_total_actual_refund_amount_currency) {
        this.seller_total_actual_refund_amount_currency = seller_total_actual_refund_amount_currency == null ? null : seller_total_actual_refund_amount_currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.buyer_total_estimated_refund_amount_value
     *
     * @return the value of return_order_list.buyer_total_estimated_refund_amount_value
     *
     * @mbggenerated
     */
    public Double getBuyer_total_estimated_refund_amount_value() {
        return buyer_total_estimated_refund_amount_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.buyer_total_estimated_refund_amount_value
     *
     * @param buyer_total_estimated_refund_amount_value the value for return_order_list.buyer_total_estimated_refund_amount_value
     *
     * @mbggenerated
     */
    public void setBuyer_total_estimated_refund_amount_value(Double buyer_total_estimated_refund_amount_value) {
        this.buyer_total_estimated_refund_amount_value = buyer_total_estimated_refund_amount_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.buyer_total_estimated_refund_amount_currency
     *
     * @return the value of return_order_list.buyer_total_estimated_refund_amount_currency
     *
     * @mbggenerated
     */
    public String getBuyer_total_estimated_refund_amount_currency() {
        return buyer_total_estimated_refund_amount_currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.buyer_total_estimated_refund_amount_currency
     *
     * @param buyer_total_estimated_refund_amount_currency the value for return_order_list.buyer_total_estimated_refund_amount_currency
     *
     * @mbggenerated
     */
    public void setBuyer_total_estimated_refund_amount_currency(String buyer_total_estimated_refund_amount_currency) {
        this.buyer_total_estimated_refund_amount_currency = buyer_total_estimated_refund_amount_currency == null ? null : buyer_total_estimated_refund_amount_currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.buyer_total_actual_refund_amount_value
     *
     * @return the value of return_order_list.buyer_total_actual_refund_amount_value
     *
     * @mbggenerated
     */
    public Double getBuyer_total_actual_refund_amount_value() {
        return buyer_total_actual_refund_amount_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.buyer_total_actual_refund_amount_value
     *
     * @param buyer_total_actual_refund_amount_value the value for return_order_list.buyer_total_actual_refund_amount_value
     *
     * @mbggenerated
     */
    public void setBuyer_total_actual_refund_amount_value(Double buyer_total_actual_refund_amount_value) {
        this.buyer_total_actual_refund_amount_value = buyer_total_actual_refund_amount_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.buyer_total_refund_actual_refund_amount_currency
     *
     * @return the value of return_order_list.buyer_total_refund_actual_refund_amount_currency
     *
     * @mbggenerated
     */
    public String getBuyer_total_refund_actual_refund_amount_currency() {
        return buyer_total_refund_actual_refund_amount_currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.buyer_total_refund_actual_refund_amount_currency
     *
     * @param buyer_total_refund_actual_refund_amount_currency the value for return_order_list.buyer_total_refund_actual_refund_amount_currency
     *
     * @mbggenerated
     */
    public void setBuyer_total_refund_actual_refund_amount_currency(String buyer_total_refund_actual_refund_amount_currency) {
        this.buyer_total_refund_actual_refund_amount_currency = buyer_total_refund_actual_refund_amount_currency == null ? null : buyer_total_refund_actual_refund_amount_currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.seller_response_due_activity_due
     *
     * @return the value of return_order_list.seller_response_due_activity_due
     *
     * @mbggenerated
     */
    public String getSeller_response_due_activity_due() {
        return seller_response_due_activity_due;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.seller_response_due_activity_due
     *
     * @param seller_response_due_activity_due the value for return_order_list.seller_response_due_activity_due
     *
     * @mbggenerated
     */
    public void setSeller_response_due_activity_due(String seller_response_due_activity_due) {
        this.seller_response_due_activity_due = seller_response_due_activity_due == null ? null : seller_response_due_activity_due.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.seller_response_due_respond_by_date_value
     *
     * @return the value of return_order_list.seller_response_due_respond_by_date_value
     *
     * @mbggenerated
     */
    public Date getSeller_response_due_respond_by_date_value() {
        return seller_response_due_respond_by_date_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.seller_response_due_respond_by_date_value
     *
     * @param seller_response_due_respond_by_date_value the value for return_order_list.seller_response_due_respond_by_date_value
     *
     * @mbggenerated
     */
    public void setSeller_response_due_respond_by_date_value(Date seller_response_due_respond_by_date_value) {
        this.seller_response_due_respond_by_date_value = seller_response_due_respond_by_date_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.buyer_response_due_activity_due
     *
     * @return the value of return_order_list.buyer_response_due_activity_due
     *
     * @mbggenerated
     */
    public String getBuyer_response_due_activity_due() {
        return buyer_response_due_activity_due;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.buyer_response_due_activity_due
     *
     * @param buyer_response_due_activity_due the value for return_order_list.buyer_response_due_activity_due
     *
     * @mbggenerated
     */
    public void setBuyer_response_due_activity_due(String buyer_response_due_activity_due) {
        this.buyer_response_due_activity_due = buyer_response_due_activity_due == null ? null : buyer_response_due_activity_due.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.buyer_response_due_respond_by_date_value
     *
     * @return the value of return_order_list.buyer_response_due_respond_by_date_value
     *
     * @mbggenerated
     */
    public Date getBuyer_response_due_respond_by_date_value() {
        return buyer_response_due_respond_by_date_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.buyer_response_due_respond_by_date_value
     *
     * @param buyer_response_due_respond_by_date_value the value for return_order_list.buyer_response_due_respond_by_date_value
     *
     * @mbggenerated
     */
    public void setBuyer_response_due_respond_by_date_value(Date buyer_response_due_respond_by_date_value) {
        this.buyer_response_due_respond_by_date_value = buyer_response_due_respond_by_date_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.buyer_escalation_eligibility_info_start_time
     *
     * @return the value of return_order_list.buyer_escalation_eligibility_info_start_time
     *
     * @mbggenerated
     */
    public Date getBuyer_escalation_eligibility_info_start_time() {
        return buyer_escalation_eligibility_info_start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.buyer_escalation_eligibility_info_start_time
     *
     * @param buyer_escalation_eligibility_info_start_time the value for return_order_list.buyer_escalation_eligibility_info_start_time
     *
     * @mbggenerated
     */
    public void setBuyer_escalation_eligibility_info_start_time(Date buyer_escalation_eligibility_info_start_time) {
        this.buyer_escalation_eligibility_info_start_time = buyer_escalation_eligibility_info_start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.buyer_escalation_eligibility_info_end_time
     *
     * @return the value of return_order_list.buyer_escalation_eligibility_info_end_time
     *
     * @mbggenerated
     */
    public Date getBuyer_escalation_eligibility_info_end_time() {
        return buyer_escalation_eligibility_info_end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.buyer_escalation_eligibility_info_end_time
     *
     * @param buyer_escalation_eligibility_info_end_time the value for return_order_list.buyer_escalation_eligibility_info_end_time
     *
     * @mbggenerated
     */
    public void setBuyer_escalation_eligibility_info_end_time(Date buyer_escalation_eligibility_info_end_time) {
        this.buyer_escalation_eligibility_info_end_time = buyer_escalation_eligibility_info_end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.buyer_escalation_eligibility_info_eligible
     *
     * @return the value of return_order_list.buyer_escalation_eligibility_info_eligible
     *
     * @mbggenerated
     */
    public Boolean getBuyer_escalation_eligibility_info_eligible() {
        return buyer_escalation_eligibility_info_eligible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.buyer_escalation_eligibility_info_eligible
     *
     * @param buyer_escalation_eligibility_info_eligible the value for return_order_list.buyer_escalation_eligibility_info_eligible
     *
     * @mbggenerated
     */
    public void setBuyer_escalation_eligibility_info_eligible(Boolean buyer_escalation_eligibility_info_eligible) {
        this.buyer_escalation_eligibility_info_eligible = buyer_escalation_eligibility_info_eligible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.seller_escalation_eligibility_Info_start_time
     *
     * @return the value of return_order_list.seller_escalation_eligibility_Info_start_time
     *
     * @mbggenerated
     */
    public Date getSeller_escalation_eligibility_Info_start_time() {
        return seller_escalation_eligibility_Info_start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.seller_escalation_eligibility_Info_start_time
     *
     * @param seller_escalation_eligibility_Info_start_time the value for return_order_list.seller_escalation_eligibility_Info_start_time
     *
     * @mbggenerated
     */
    public void setSeller_escalation_eligibility_Info_start_time(Date seller_escalation_eligibility_Info_start_time) {
        this.seller_escalation_eligibility_Info_start_time = seller_escalation_eligibility_Info_start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.seller_escalation_eligibility_Info_end_time
     *
     * @return the value of return_order_list.seller_escalation_eligibility_Info_end_time
     *
     * @mbggenerated
     */
    public Date getSeller_escalation_eligibility_Info_end_time() {
        return seller_escalation_eligibility_Info_end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.seller_escalation_eligibility_Info_end_time
     *
     * @param seller_escalation_eligibility_Info_end_time the value for return_order_list.seller_escalation_eligibility_Info_end_time
     *
     * @mbggenerated
     */
    public void setSeller_escalation_eligibility_Info_end_time(Date seller_escalation_eligibility_Info_end_time) {
        this.seller_escalation_eligibility_Info_end_time = seller_escalation_eligibility_Info_end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.seller_escalation_eligibility_info_eligible
     *
     * @return the value of return_order_list.seller_escalation_eligibility_info_eligible
     *
     * @mbggenerated
     */
    public Boolean getSeller_escalation_eligibility_info_eligible() {
        return seller_escalation_eligibility_info_eligible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.seller_escalation_eligibility_info_eligible
     *
     * @param seller_escalation_eligibility_info_eligible the value for return_order_list.seller_escalation_eligibility_info_eligible
     *
     * @mbggenerated
     */
    public void setSeller_escalation_eligibility_info_eligible(Boolean seller_escalation_eligibility_info_eligible) {
        this.seller_escalation_eligibility_info_eligible = seller_escalation_eligibility_info_eligible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.seller_available_options
     *
     * @return the value of return_order_list.seller_available_options
     *
     * @mbggenerated
     */
    public String getSeller_available_options() {
        return seller_available_options;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.seller_available_options
     *
     * @param seller_available_options the value for return_order_list.seller_available_options
     *
     * @mbggenerated
     */
    public void setSeller_available_options(String seller_available_options) {
        this.seller_available_options = seller_available_options == null ? null : seller_available_options.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.buyer_available_options
     *
     * @return the value of return_order_list.buyer_available_options
     *
     * @mbggenerated
     */
    public String getBuyer_available_options() {
        return buyer_available_options;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.buyer_available_options
     *
     * @param buyer_available_options the value for return_order_list.buyer_available_options
     *
     * @mbggenerated
     */
    public void setBuyer_available_options(String buyer_available_options) {
        this.buyer_available_options = buyer_available_options == null ? null : buyer_available_options.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.return_policy_multiple_return_address
     *
     * @return the value of return_order_list.return_policy_multiple_return_address
     *
     * @mbggenerated
     */
    public Boolean getReturn_policy_multiple_return_address() {
        return return_policy_multiple_return_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.return_policy_multiple_return_address
     *
     * @param return_policy_multiple_return_address the value for return_order_list.return_policy_multiple_return_address
     *
     * @mbggenerated
     */
    public void setReturn_policy_multiple_return_address(Boolean return_policy_multiple_return_address) {
        this.return_policy_multiple_return_address = return_policy_multiple_return_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.return_policy_rmarequired
     *
     * @return the value of return_order_list.return_policy_rmarequired
     *
     * @mbggenerated
     */
    public Boolean getReturn_policy_rmarequired() {
        return return_policy_rmarequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.return_policy_rmarequired
     *
     * @param return_policy_rmarequired the value for return_order_list.return_policy_rmarequired
     *
     * @mbggenerated
     */
    public void setReturn_policy_rmarequired(Boolean return_policy_rmarequired) {
        this.return_policy_rmarequired = return_policy_rmarequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.flags
     *
     * @return the value of return_order_list.flags
     *
     * @mbggenerated
     */
    public String getFlags() {
        return flags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.flags
     *
     * @param flags the value for return_order_list.flags
     *
     * @mbggenerated
     */
    public void setFlags(String flags) {
        this.flags = flags == null ? null : flags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column return_order_list.timeout_date_value
     *
     * @return the value of return_order_list.timeout_date_value
     *
     * @mbggenerated
     */
    public Date getTimeout_date_value() {
        return timeout_date_value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column return_order_list.timeout_date_value
     *
     * @param timeout_date_value the value for return_order_list.timeout_date_value
     *
     * @mbggenerated
     */
    public void setTimeout_date_value(Date timeout_date_value) {
        this.timeout_date_value = timeout_date_value;
    }
}